// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNlwgLnp9N83NVZGiywqGNSez3zRGo-Go',
    appId: '1:479394296879:web:bc6aa35e7ec66613be42da',
    messagingSenderId: '479394296879',
    projectId: 'messenger-a-25d32',
    authDomain: 'messenger-a-25d32.firebaseapp.com',
    storageBucket: 'messenger-a-25d32.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCi5hxAN3Y_nAPIkzbyoLVSwXRuLi3-UBk',
    appId: '1:479394296879:android:4e46c2267b3200dabe42da',
    messagingSenderId: '479394296879',
    projectId: 'messenger-a-25d32',
    storageBucket: 'messenger-a-25d32.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVC9lTMI48MHyuIoHao_h6fUnNq451ZRY',
    appId: '1:479394296879:ios:3278ffa3b7881372be42da',
    messagingSenderId: '479394296879',
    projectId: 'messenger-a-25d32',
    storageBucket: 'messenger-a-25d32.appspot.com',
    iosBundleId: 'com.example.massengerApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAVC9lTMI48MHyuIoHao_h6fUnNq451ZRY',
    appId: '1:479394296879:ios:3278ffa3b7881372be42da',
    messagingSenderId: '479394296879',
    projectId: 'messenger-a-25d32',
    storageBucket: 'messenger-a-25d32.appspot.com',
    iosBundleId: 'com.example.massengerApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNlwgLnp9N83NVZGiywqGNSez3zRGo-Go',
    appId: '1:479394296879:web:465ca59eda52e47bbe42da',
    messagingSenderId: '479394296879',
    projectId: 'messenger-a-25d32',
    authDomain: 'messenger-a-25d32.firebaseapp.com',
    storageBucket: 'messenger-a-25d32.appspot.com',
  );
}
